config/routes.rb
Rails.application.routes.draw do
  get 'form/new'
  get 'form/create'
  get 'projects/dashboard'

  root 'projects#dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates :title, :description, :state, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only: :dashboard
end

app/controllers/form_controller.rb
class FormController < ApplicationController
  def new
  end

  def create
    @project = Project.create(title: params[:title], description: params[:description], start_date: params[:start_date], deadline: params[:deadline], state: params[:state])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def dashboard
    if params[:state].present?
      @project = Project.where('state = ?', params[:state])
    else
      @project = Project.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/form/create.html.erb
<% if @project.errors.any? %>
    <div id="error_explanation">
        <h2>
            <%= pluralize(@project.errors.count, "error") %>
                prohibited this user from being saved:
        </h2>
        <ul>
        <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
    <%= link_to 'Try again', form_new_path %>
<% else %>
<h1> Has creado el proyecto con éxito </h1>
<%= link_to 'Crear nuevo proyecto', form_new_path %>
<% end %>

app/views/form/new.html.erb
<h1>Crear un nuevo proyecto</h1>
<h5>Recuerda completar los campos "Nombre del proyecto", "Descripción" y "Estado" para evitar errores</h5>
<form method="get" action="/form/create" id="create_posts">
    <div class="form-group">
        <label for="title">Nombre del proyecto</label>
        <input name="title" type="text" class="form-control col-5" id="title" placeholder="Ingresa el título del proyecto">
    </div>
    <div class="form-group">
        <label for="description">Descripción del proyecto</label>
        <textarea name="description" type="text" class="form-control col-5" placeholder="Ingresa la descripción del proyecto"></textarea>
    </div>
    <div class="form-group">
        <label for="start_date">Fecha de inicio del proyecto</label>
        <input name="start_date" type="date" class="form-control col-3">
    </div>
    <div class="form-group">
        <label for="deadline">Fecha final del proyecto</label>
        <input name="deadline" type="date" class="form-control col-3">
    </div>
    <div class="input-group">
        <select name="state" class="custom-select col-3" id="inputGroupSelect04">
            <option selected>Seleccionar estado del proyecto</option>
            <option value="Propuesta">Propuesta</option>
            <option value="En progreso">En progreso</option>
            <option value="Terminado">Terminado</option>
        </select>
    </div>
    

    <button type="submit" class="btn btn-primary mt-3">Crear Proyecto</button>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gestorproyectos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar"%>
    <div class="container pt-5">
      <%= yield %>
    </div>  
  </body>
</html>

app/views/projects/dashboard.html.erb
<h1>Listado de proyectos</h1>
<h2>Filtrar por estado:</h2>
<form method="get" action="<%= projects_dashboard_path %>">
    <div class="input-group">
        <select name="state" class="custom-select col-3" id="inputGroupSelect04">
            <option selected value="">Seleccionar estado del proyecto</option>
            <option value="Propuesta">Propuesta</option>
            <option value="En progreso">En progreso</option>
            <option value="Terminado">Terminado</option>
            <option value="">Mostrar todos</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary mt-3 mb-3">Filtrar</button>
</form>

<div class="card-columns">
   <% @project.each do |project| %>
        <div class="card">
            <h3 class="card-title text-center"><%= project.title %></h3>
            <div class="card-body">
                <p class="card-text"><%= project.description %></p>
                <h6 class="card-subtitle mb-2 text-muted"><td><%= project.start_date %></td></h6>
                <h6 class="card-subtitle mb-2 text-muted"><td><%= project.deadline %></td></h6>
                <h6 class="card-subtitle mb-2 text-muted"><td><%= project.state %></td></h6>
            </div>
        </div>
        <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top mb-5">
  <a class="navbar-brand" href="#">Gestor de proyectos</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Home", root_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Crear artículo", form_new_path, class:'nav-link' %>
      </li>   
  </div>
</nav>